/**
 * Controlled Taxonomy for Instagram Outreach OS
 * Defines Role signals, Research/Problem signals, Niche vocabulary, and Exclusion filters.
 */

export const ROLE_KEYWORDS = [
  'content creator',
  'content strategist',
  'content strategy',
  'social media manager',
  'social media strategist',
  'content marketing',
  'ugc creator',
  'creator educator',
  'personal brand',
  'personal branding',
  'copywriter',
  'brand strategist',
  'marketing strategist',
  'growth marketer',
  'marketing consultant',
  'founder',
  'co-founder',
  'solopreneur',
  'entrepreneur',
  'coach',
  'consultant',
  'educator',
  'teacher',
  'newsletter',
  'podcast',
  'podcaster',
  'creator economy',
  'agency',
  'creative director',
  'community builder',
  'video editor',
  'course creator',
  'digital creator'
] as const;

export const RESEARCH_KEYWORDS = [
  'content ideas',
  'content research',
  'research',
  'content strategy',
  'hooks',
  'hook ideas',
  'scripts',
  'swipe file',
  'content inspiration',
  'references',
  'resources',
  'tools',
  'prompts',
  'save this',
  'save this reel',
  'save this post',
  'bookmark this',
  'come back to this',
  'for later',
  'use this later',
  'templates',
  'framework',
  'frameworks',
  'examples',
  'breakdown',
  'case study',
  'lessons',
  'learnings',
  'ideas',
  'trends',
  'content pillars',
  'content calendar',
  'content workflow',
  'content system',
  'content repurposing',
  'content planning',
  'creative research',
  'competitor research',
  'inspiration',
  'knowledge',
  'notes',
  'learning',
  'curation',
  'curated'
] as const;

export const NICHE_KEYWORDS = [
  'ai',
  'artificial intelligence',
  'generative ai',
  'chatgpt',
  'claude',
  'automation',
  'saas',
  'software',
  'technology',
  'startups',
  'startup',
  'founder',
  'entrepreneurship',
  'business',
  'b2b',
  'marketing',
  'growth',
  'sales',
  'copywriting',
  'branding',
  'content marketing',
  'social media',
  'creator economy',
  'personal branding',
  'product',
  'product management',
  'ux',
  'ui',
  'design',
  'productivity',
  'career',
  'leadership',
  'consulting',
  'education',
  'writing',
  'newsletter',
  'creator tools',
  'creator business',
  'online business',
  'digital products',
  'finance',
  'tech',
  'developer'
] as const;

export const EXCLUDED_KEYWORDS = [
  'meme',
  'memes',
  'comedy',
  'viral clips',
  'entertainment',
  'fan page',
  'fanpage',
  'fandom',
  'celebrity',
  'quotes daily',
  'repost',
  'reposts',
  'aggregator',
  'giveaway',
  'giveaways',
  'win free',
  'movie clips',
  'tv clips',
  'music edits',
  'horoscope',
  'zodiac',
  'crypto pump',
  'signals forex',
  'casino',
  'betting',
  'dropshipping store',
  'spam',
  'follow back',
  'engagement pod',
  'faceless theme'
] as const;
